# Generated by Django 3.2.16 on 2023-03-05 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('emails', models.CharField(blank=True, max_length=4000, null=True)),
            ],
            options={
                'db_table': 'branch',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DeliveryMethod',
            fields=[
                ('dm_key', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('del_med', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'delivery_method',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InspectionCode',
            fields=[
                ('inspect_code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('detail', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'inspection_code',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IrOrder',
            fields=[
                ('ir_index', models.BigIntegerField(primary_key=True, serialize=False)),
                ('article_number', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('quantity', models.BigIntegerField(blank=True, null=True)),
                ('order_nm', models.CharField(blank=True, max_length=100, null=True)),
                ('arrival_date', models.CharField(blank=True, max_length=100, null=True)),
                ('subinventory', models.CharField(blank=True, max_length=100, null=True)),
                ('ship_date', models.CharField(blank=True, max_length=100, null=True)),
                ('comments', models.CharField(blank=True, max_length=2000, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('timeline', models.CharField(blank=True, max_length=4000, null=True)),
            ],
            options={
                'db_table': 'ir_order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LocalList',
            fields=[
                ('lc_index', models.BigIntegerField(primary_key=True, serialize=False)),
                ('arrival_date', models.CharField(blank=True, max_length=50, null=True)),
                ('article_number', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('quantity', models.BigIntegerField(blank=True, null=True)),
                ('so_no', models.CharField(blank=True, max_length=100, null=True)),
                ('receipt_no', models.CharField(blank=True, max_length=50, null=True)),
                ('pic', models.CharField(blank=True, max_length=50, null=True)),
                ('customer', models.CharField(blank=True, max_length=100, null=True)),
                ('ship_date', models.CharField(blank=True, max_length=1000, null=True)),
                ('pod_date', models.CharField(blank=True, max_length=100, null=True)),
                ('comments', models.CharField(blank=True, max_length=4000, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('timeline', models.CharField(blank=True, max_length=4000, null=True)),
            ],
            options={
                'db_table': 'local_list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MailDetail',
            fields=[
                ('ml_sub', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('ml_type_nm', models.BigIntegerField()),
                ('std_day', models.CharField(max_length=50)),
                ('ml_body', models.CharField(blank=True, max_length=2000, null=True)),
            ],
            options={
                'db_table': 'mail_detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MailStatus',
            fields=[
                ('ms_index', models.BigAutoField(primary_key=True, serialize=False)),
                ('ml_status', models.CharField(max_length=50)),
                ('up_time', models.CharField(max_length=100)),
                ('ml_bin', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'mail_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MailType',
            fields=[
                ('ml_type_nm', models.BigIntegerField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'mail_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PodMethod',
            fields=[
                ('pod_key', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('pod_med', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'pod_method',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProdPose',
            fields=[
                ('subinventory', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('comments', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'prod_pose',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('article_number', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('prod_centre', models.CharField(blank=True, max_length=500, null=True)),
                ('prod_group', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.CharField(max_length=500)),
                ('prod_status_type', models.CharField(blank=True, max_length=200, null=True)),
                ('bin_cur', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('svc_key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('fe_name', models.CharField(blank=True, max_length=100, null=True)),
                ('fe_initial', models.CharField(blank=True, max_length=100, null=True)),
                ('req_day', models.CharField(blank=True, max_length=100, null=True)),
                ('req_time', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('del_met', models.CharField(blank=True, max_length=100, null=True)),
                ('is_return', models.CharField(blank=True, max_length=50, null=True)),
                ('is_urgent', models.CharField(blank=True, max_length=50, null=True)),
                ('recipient', models.CharField(blank=True, max_length=50, null=True)),
                ('contact', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_sub', models.CharField(blank=True, max_length=50, null=True)),
                ('del_instruction', models.CharField(blank=True, max_length=2000, null=True)),
                ('parts', models.CharField(blank=True, max_length=4000, null=True)),
                ('std_day', models.CharField(blank=True, max_length=100, null=True)),
                ('timeline', models.CharField(blank=True, max_length=4000, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'service_request',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShipmentInformation',
            fields=[
                ('si_index', models.BigIntegerField(primary_key=True, serialize=False)),
                ('awb_no', models.CharField(blank=True, max_length=100, null=True)),
                ('trip_no', models.CharField(blank=True, max_length=100, null=True)),
                ('shipment_nm', models.CharField(blank=True, max_length=100, null=True)),
                ('nm_of_package', models.CharField(blank=True, max_length=50, null=True)),
                ('invoice_date', models.CharField(blank=True, max_length=100, null=True)),
                ('order_nm', models.CharField(blank=True, max_length=50, null=True)),
                ('order_total', models.CharField(blank=True, max_length=100, null=True)),
                ('unit_price', models.CharField(blank=True, max_length=100, null=True)),
                ('ship_to', models.CharField(blank=True, max_length=100, null=True)),
                ('arrival_date', models.CharField(blank=True, max_length=100, null=True)),
                ('ship_date', models.CharField(blank=True, max_length=100, null=True)),
                ('pod_date', models.CharField(blank=True, max_length=100, null=True)),
                ('for_free', models.CharField(blank=True, max_length=50, null=True)),
                ('remark', models.CharField(blank=True, max_length=2000, null=True)),
                ('parcels_no', models.CharField(blank=True, max_length=100, null=True)),
                ('comments', models.CharField(blank=True, max_length=2000, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('timeline', models.CharField(blank=True, max_length=4000, null=True)),
            ],
            options={
                'db_table': 'shipment_information',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SoOut',
            fields=[
                ('so_index', models.BigAutoField(primary_key=True, serialize=False)),
                ('sht_row_idx', models.CharField(max_length=2000)),
                ('person_in_charge', models.CharField(max_length=100)),
                ('ship_date', models.CharField(max_length=50)),
                ('dm_key', models.CharField(max_length=50)),
                ('pod_key', models.CharField(max_length=50)),
                ('is_local', models.CharField(max_length=2000)),
                ('pod_date', models.CharField(blank=True, max_length=50, null=True)),
                ('timeline', models.CharField(max_length=4000)),
            ],
            options={
                'db_table': 'so_out',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SvcBin',
            fields=[
                ('bin_index', models.BigAutoField(primary_key=True, serialize=False)),
                ('article_number', models.CharField(blank=True, max_length=100, null=True)),
                ('bin', models.CharField(blank=True, max_length=100, null=True)),
                ('bin_old', models.CharField(blank=True, max_length=100, null=True)),
                ('subinventory', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'svc_bin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SystemStock',
            fields=[
                ('ss_key', models.BigAutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.BigIntegerField()),
                ('in_date', models.CharField(max_length=50)),
                ('expiry_date', models.CharField(blank=True, max_length=50, null=True)),
                ('currency', models.CharField(blank=True, max_length=50, null=True)),
                ('lot_cost', models.FloatField(blank=True, null=True)),
                ('lot_cost_in_usd', models.FloatField(blank=True, null=True)),
                ('std_day', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'system_stock',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('test', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('emails', models.CharField(blank=True, max_length=4000, null=True)),
                ('up_time', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'test',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TotalStock',
            fields=[
                ('ts_key', models.BigAutoField(primary_key=True, serialize=False)),
                ('article_number', models.CharField(max_length=50)),
                ('subinventory', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.BigIntegerField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('prod_centre', models.CharField(blank=True, max_length=500, null=True)),
                ('prod_group', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('prod_status_type', models.CharField(blank=True, max_length=100, null=True)),
                ('bin_cur', models.CharField(blank=True, max_length=100, null=True)),
                ('std_day', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('state_time', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'total_stock',
                'managed': False,
            },
        ),
    ]
