# Generated by Django 3.2.16 on 2023-03-11 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_svctool'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyInBr',
            fields=[
                ('dir_key', models.BigAutoField(primary_key=True, serialize=False)),
                ('branch_name', models.CharField(blank=True, max_length=100, null=True)),
                ('std_day', models.CharField(blank=True, max_length=100, null=True)),
                ('qty', models.BigIntegerField(blank=True, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'daily_in_br',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DailyInIr',
            fields=[
                ('dir_key', models.BigAutoField(primary_key=True, serialize=False)),
                ('std_day', models.CharField(blank=True, max_length=100, null=True)),
                ('qty', models.BigIntegerField(blank=True, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'daily_in_ir',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DailyInLc',
            fields=[
                ('dil_key', models.BigAutoField(primary_key=True, serialize=False)),
                ('std_day', models.CharField(blank=True, max_length=100, null=True)),
                ('qty', models.BigIntegerField(blank=True, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'daily_in_lc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DailyInSo',
            fields=[
                ('dis_key', models.BigAutoField(primary_key=True, serialize=False)),
                ('std_day', models.CharField(blank=True, max_length=100, null=True)),
                ('qty', models.BigIntegerField(blank=True, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'daily_in_so',
                'managed': False,
            },
        ),
    ]
