# Generated by Django 3.2.16 on 2023-03-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_dailyinbr_dailyinir_dailyinlc_dailyinso'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySoOut',
            fields=[
                ('dso_key', models.BigAutoField(primary_key=True, serialize=False)),
                ('ship_date', models.CharField(blank=True, max_length=100, null=True)),
                ('del_med', models.CharField(blank=True, max_length=100, null=True)),
                ('qty', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'daily_so_out',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PodDelay',
            fields=[
                ('pd_key', models.BigAutoField(primary_key=True, serialize=False)),
                ('take_hours', models.BigIntegerField(blank=True, null=True)),
                ('std_day', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'pod_delay',
                'managed': False,
            },
        ),
    ]
