# Generated by Django 3.2.16 on 2023-02-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TotalStock',
            fields=[
                ('ts_key', models.BigAutoField(primary_key=True, serialize=False)),
                ('article_number', models.CharField(max_length=50)),
                ('subinventory', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.BigIntegerField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('prod_centre', models.CharField(blank=True, max_length=500, null=True)),
                ('prod_group', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('prod_status_type', models.CharField(blank=True, max_length=100, null=True)),
                ('bin_cur', models.CharField(blank=True, max_length=100, null=True)),
                ('std_day', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'total_stock',
                'managed': False,
            },
        ),
    ]
