# Generated by Django 3.2.16 on 2023-03-06 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_userdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='SvcTool',
            fields=[
                ('tool_index', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(blank=True, max_length=200, null=True)),
                ('system', models.CharField(blank=True, max_length=200, null=True)),
                ('tool_nm', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('picture', models.CharField(blank=True, max_length=100, null=True)),
                ('serial_nm', models.CharField(blank=True, max_length=500, null=True)),
                ('calibration', models.CharField(blank=True, max_length=500, null=True)),
                ('on_hand', models.CharField(blank=True, max_length=500, null=True)),
                ('ship_date', models.CharField(blank=True, max_length=500, null=True)),
                ('tool_bin', models.CharField(blank=True, max_length=500, null=True)),
                ('comments', models.CharField(blank=True, max_length=500, null=True)),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'svc_tool',
                'managed': False,
            },
        ),
    ]
